# Generated by Django 4.2.7 on 2023-11-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
