# Generated by Django 4.2.7 on 2023-11-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.CharField(max_length=250, null=True, verbose_name='Написать комментарий '),
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
